package com.virjar.vscrawler.core.net.useragent;

import com.google.common.collect.ImmutableList;

public interface UAConstants {

    ImmutableList<String> iphoneDeviceNums = ImmutableList.<String>builder()
            .add("Mobile/10B329")
            .add("Mobile/11B554a")
            .add("Mobile/11D167")
            .add("Mobile/12A365")
            .add("Mobile/12B411")
            .add("Mobile/12B435")
            .add("Mobile/12B440")
            .add("Mobile/12D508")
            .add("Mobile/12F70")
            .add("Mobile/12H143")
            .add("Mobile/12H321")
            .add("Mobile/13A342")
            .add("Mobile/13A452")
            .add("Mobile/13B143")
            .add("Mobile/13C75")
            .add("Mobile/13D15")
            .add("Mobile/13E233")
            .add("Mobile/13E234")
            .add("Mobile/13E238")
            .add("Mobile/13F69")
            .add("Mobile/13G34")
            .add("Mobile/13G35")
            .add("Mobile/13G36")
            .add("Mobile/14A346")
            .add("Mobile/14A403")
            .add("Mobile/14A456")
            .add("Mobile/14A551")
            .add("Mobile/14B100")
            .add("Mobile/14B150")
            .add("Mobile/14B72")
            .add("Mobile/14B72c")
            .add("Mobile/14C92")
            .add("Mobile/14D27")
            .add("Mobile/14E277")
            .add("Mobile/14E304")
            .add("Mobile/14F89")
            .add("Mobile/9A334")
            .build();

    ImmutableList<String> iphoneDevices = ImmutableList.<String>builder()
            .add("iPhone 5SGLOBAL; CPU iPhone OS 10_1_1 like Mac OS X")
            .add("iPhone 5SGLOBAL; CPU iPhone OS 10_2_1 like Mac OS X")
            .add("iPhone 5SGLOBAL; CPU iPhone OS 10_3_1 like Mac OS X")
            .add("iPhone 5SGLOBAL; CPU iPhone OS 10_3_2 like Mac OS X")
            .add("iPhone 5SGLOBAL; CPU iPhone OS 8_3 like Mac OS X")
            .add("iPhone 5SGLOBAL; CPU iPhone OS 8_4 like Mac OS X")
            .add("iPhone 5SGLOBAL; CPU iPhone OS 9_3_4 like Mac OS X")
            .add("iPhone 5SGSM; CPU iPhone OS 8_2 like Mac OS X")
            .add("iPhone 6; CPU iPhone OS 10_0_2 like Mac OS X")
            .add("iPhone 6; CPU iPhone OS 10_1_1 like Mac OS X")
            .add("iPhone 6; CPU iPhone OS 10_2_1 like Mac OS X")
            .add("iPhone 6; CPU iPhone OS 10_3 like Mac OS X")
            .add("iPhone 6; CPU iPhone OS 10_3_1 like Mac OS X")
            .add("iPhone 6; CPU iPhone OS 10_3_2 like Mac OS X")
            .add("iPhone 6; CPU iPhone OS 8_3 like Mac OS X")
            .add("iPhone 6; CPU iPhone OS 8_4_1 like Mac OS X")
            .add("iPhone 6p; CPU iPhone OS 10_0_1 like Mac OS X")
            .add("iPhone 6p; CPU iPhone OS 10_2_1 like Mac OS X")
            .add("iPhone 6p; CPU iPhone OS 10_3_2 like Mac OS X")
            .add("iPhone 6p; CPU iPhone OS 8_1 like Mac OS X")
            .add("iPhone 6p; CPU iPhone OS 8_1_2 like Mac OS X")
            .add("iPhone 6p; CPU iPhone OS 8_4_1 like Mac OS X")
            .add("iPhone 6p; CPU iPhone OS 9_3_2 like Mac OS X")
            .add("iPhone 6p; CPU iPhone OS 9_3_5 like Mac OS X")
            .add("iPhone 6s; CPU iPhone OS 10_0_2 like Mac OS X")
            .add("iPhone 6s; CPU iPhone OS 10_1_1 like Mac OS X")
            .add("iPhone 6s; CPU iPhone OS 10_2_1 like Mac OS X")
            .add("iPhone 6s; CPU iPhone OS 10_3_1 like Mac OS X")
            .add("iPhone 6s; CPU iPhone OS 10_3_2 like Mac OS X")
            .add("iPhone 6s; CPU iPhone OS 9_1 like Mac OS X")
            .add("iPhone 6s; CPU iPhone OS 9_2_1 like Mac OS X")
            .add("iPhone 6s; CPU iPhone OS 9_3_1 like Mac OS X")
            .add("iPhone 6s; CPU iPhone OS 9_3_5 like Mac OS X")
            .add("iPhone 6sp; CPU iPhone OS 10_3_2 like Mac OS X")
            .add("iPhone 6sp; CPU iPhone OS 9_2 like Mac OS X")
            .add("iPhone 91; CPU iPhone OS 10_0 like Mac OS X")
            .add("iPhone 91; CPU iPhone OS 10_0_3 like Mac OS X")
            .add("iPhone 91; CPU iPhone OS 10_1 like Mac OS X")
            .add("iPhone 91; CPU iPhone OS 10_2 like Mac OS X")
            .add("iPhone 91; CPU iPhone OS 10_2_1 like Mac OS X")
            .add("iPhone 91; CPU iPhone OS 10_3_1 like Mac OS X")
            .add("iPhone 91; CPU iPhone OS 10_3_2 like Mac OS X")
            .add("iPhone 92; CPU iPhone OS 10_2_1 like Mac OS X")
            .add("iPhone 92; CPU iPhone OS 10_3_1 like Mac OS X")
            .add("iPhone 92; CPU iPhone OS 10_3_2 like Mac OS X")
            .add("iPhone; CPU iPhone OS 10_0 like Mac OS X")
            .add("iPhone; CPU iPhone OS 10_0_1 like Mac OS X")
            .add("iPhone; CPU iPhone OS 10_0_2 like Mac OS X")
            .add("iPhone; CPU iPhone OS 10_1 like Mac OS X")
            .add("iPhone; CPU iPhone OS 10_1_1 like Mac OS X")
            .add("iPhone; CPU iPhone OS 10_2 like Mac OS X")
            .add("iPhone; CPU iPhone OS 10_2_1 like Mac OS X")
            .add("iPhone; CPU iPhone OS 10_3 like Mac OS X")
            .add("iPhone; CPU iPhone OS 10_3_1 like Mac OS X")
            .add("iPhone; CPU iPhone OS 10_3_2 like Mac OS X")
            .add("iPhone; CPU iPhone OS 5_0 like Mac OS X")
            .add("iPhone; CPU iPhone OS 6_1_3 like Mac OS X")
            .add("iPhone; CPU iPhone OS 7_0_4 like Mac OS X")
            .add("iPhone; CPU iPhone OS 7_1 like Mac OS X")
            .add("iPhone; CPU iPhone OS 8_0 like Mac OS X")
            .add("iPhone; CPU iPhone OS 8_1_1 like Mac OS X")
            .add("iPhone; CPU iPhone OS 8_3 like Mac OS X")
            .add("iPhone; CPU iPhone OS 8_4 like Mac OS X")
            .add("iPhone; CPU iPhone OS 8_4_1 like Mac OS X")
            .add("iPhone; CPU iPhone OS 9_0 like Mac OS X")
            .add("iPhone; CPU iPhone OS 9_0_2 like Mac OS X")
            .add("iPhone; CPU iPhone OS 9_1 like Mac OS X")
            .add("iPhone; CPU iPhone OS 9_2 like Mac OS X")
            .add("iPhone; CPU iPhone OS 9_2_1 like Mac OS X")
            .add("iPhone; CPU iPhone OS 9_3 like Mac OS X")
            .add("iPhone; CPU iPhone OS 9_3_1 like Mac OS X")
            .add("iPhone; CPU iPhone OS 9_3_2 like Mac OS X")
            .add("iPhone; CPU iPhone OS 9_3_3 like Mac OS X")
            .add("iPhone; CPU iPhone OS 9_3_4 like Mac OS X")
            .add("iPhone; CPU iPhone OS 9_3_5 like Mac OS X")
            .build();

    ImmutableList<String> androidDevices = ImmutableList.<String>builder()
            .add("Linux; Android 4.3; X9007 Build/JLS36C; wv")
            .add("Linux; Android 4.3; X9077 Build/JLS36C; wv")
            .add("Linux; Android 4.4.2; 2014501 Build/KOT49H; wv")
            .add("Linux; Android 4.4.2; CHM-TL00H Build/HonorCHM-TL00H; wv")
            .add("Linux; Android 4.4.2; H60-L01 Build/HDH60-L01; wv")
            .add("Linux; Android 4.4.2; HONOR H30-L01 Build/HonorH30-L01; wv")
            .add("Linux; Android 4.4.2; HUAWEI P7-L07 Build/HuaweiP7-L07")
            .add("Linux; Android 4.4.2; PE-TL20 Build/HuaweiPE-TL20; wv")
            .add("Linux; Android 4.4.2; vivo X3V Build/KVT49L; wv")
            .add("Linux; Android 4.4.4; HM 2A Build/KTU84Q; wv")
            .add("Linux; Android 4.4.4; HM NOTE 1S Build/KTU84P; wv")
            .add("Linux; Android 4.4.4; OPPO R7 Build/KTU84P; wv")
            .add("Linux; Android 4.4.4; OPPO R7s Build/KTU84P; wv")
            .add("Linux; Android 4.4.4; R7c Build/KTU84P; wv")
            .add("Linux; Android 4.4.4; R8207 Build/KTU84P; wv")
            .add("Linux; Android 4.4.4; vivo X5V Build/KTU84P; wv")
            .add("Linux; Android 4.4.4; vivo Y27 Build/KTU84P; wv")
            .add("Linux; Android 5.0.1; M040 Build/LRX22C")
            .add("Linux; Android 5.0.2; Redmi Note 2 Build/LRX22G; wv")
            .add("Linux; Android 5.0.2; Redmi Note 3 Build/LRX22G")
            .add("Linux; Android 5.0.2; Redmi Note 3 Build/LRX22G; wv")
            .add("Linux; Android 5.0.2; SM-A5000 Build/LRX22G; wv")
            .add("Linux; Android 5.0.2; vivo X5M Build/LRX22G; wv")
            .add("Linux; Android 5.0.2; vivo X6A Build/LRX22G; wv")
            .add("Linux; Android 5.0.2; vivo Y31A Build/LRX22G; wv")
            .add("Linux; Android 5.0; CHE-TL00H Build/HonorCHE-TL00H")
            .add("Linux; Android 5.0; SM-G9009D Build/LRX21T; wv")
            .add("Linux; Android 5.0; SM-G9009W Build/LRX21T; wv")
            .add("Linux; Android 5.0; SM-N9008V Build/LRX21V; wv")
            .add("Linux; Android 5.0; vivo Y33 Build/LRX21M; wv")
            .add("Linux; Android 5.1.1; HUAWEI M2-A01L Build/HUAWEIM2-A01L; wv")
            .add("Linux; Android 5.1.1; KIW-AL10 Build/HONORKIW-AL10; wv")
            .add("Linux; Android 5.1.1; MI NOTE Pro Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; MX4 Pro Build/LMY48W")
            .add("Linux; Android 5.1.1; OPPO A33 Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; OPPO A33t Build/LMY47V")
            .add("Linux; Android 5.1.1; OPPO A53 Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; OPPO R7sPlus Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; OPPO R7sm Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; OPPO R9 Plusm A Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; R7Plusm Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; Redmi 3 Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; SM-A8000 Build/LMY47X; wv")
            .add("Linux; Android 5.1.1; SM801 Build/LMY47V")
            .add("Linux; Android 5.1.1; SM801 Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; YQ601 Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; vivo V3Max A Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; vivo X6S A Build/LMY47V")
            .add("Linux; Android 5.1.1; vivo X6S A Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; vivo X6SPlus A Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; vivo X7 Build/LMY47V; wv")
            .add("Linux; Android 5.1.1; vivo Y51A Build/LMY47V; wv")
            .add("Linux; Android 5.1; HUAWEI RIO-TL00 Build/HUAWEIRIO-TL00; wv")
            .add("Linux; Android 5.1; MX4 Build/LMY47I")
            .add("Linux; Android 5.1; MX4 Build/LMY47I; wv")
            .add("Linux; Android 5.1; MX5 Build/LMY47I; wv")
            .add("Linux; Android 5.1; OPPO A37m Build/LMY47I")
            .add("Linux; Android 5.1; OPPO A37m Build/LMY47I; wv")
            .add("Linux; Android 5.1; OPPO A59m Build/LMY47I; wv")
            .add("Linux; Android 5.1; OPPO A59s Build/LMY47I; wv")
            .add("Linux; Android 5.1; OPPO R9m Build/LMY47I; wv")
            .add("Linux; Android 5.1; OPPO R9t Build/LMY47I")
            .add("Linux; Android 5.1; OPPO R9t Build/LMY47I; wv")
            .add("Linux; Android 5.1; OPPO R9tm Build/LMY47I; wv")
            .add("Linux; Android 5.1; PRO 5 Build/LMY47D")
            .add("Linux; Android 5.1; PRO 5 Build/LMY47D; wv")
            .add("Linux; Android 5.1; SM-J5008 Build/LMY47O; wv")
            .add("Linux; Android 5.1; m1 metal Build/LMY47I")
            .add("Linux; Android 5.1; m1 metal Build/LMY47I; wv")
            .add("Linux; Android 5.1; m2 note Build/LMY47D")
            .add("Linux; Android 5.1; m2 note Build/LMY47D; wv")
            .add("Linux; Android 5.1; vivo X6D Build/LMY47I")
            .add("Linux; Android 5.1; vivo X6D Build/LMY47I; wv")
            .add("Linux; Android 5.1; vivo X6L Build/LMY47I; wv")
            .add("Linux; Android 5.1; vivo X6Plus D Build/LMY47I; wv")
            .add("Linux; Android 6.0.1; KIW-AL10 Build/HONORKIW-AL10; wv")
            .add("Linux; Android 6.0.1; MI 5s Build/MXB48T; wv")
            .add("Linux; Android 6.0.1; MI 5s Plus Build/MXB48T")
            .add("Linux; Android 6.0.1; MI 5s Plus Build/MXB48T; wv")
            .add("Linux; Android 6.0.1; MI MAX Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; MI NOTE LTE Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; Mi Note 2 Build/MXB48T; wv")
            .add("Linux; Android 6.0.1; OPPO A57 Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; OPPO A57t Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; OPPO R9s Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; OPPO R9s Plus Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; OPPO R9sk Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; OPPO R9st Build/MMB29M")
            .add("Linux; Android 6.0.1; Redmi 3S Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; Redmi 4 Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; Redmi 4X Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; Redmi Note 3 Build/MMB29M")
            .add("Linux; Android 6.0.1; Redmi Note 3 Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; Redmi Note 4X Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; SM-A8000 Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; SM-A9000 Build/MMB29M")
            .add("Linux; Android 6.0.1; SM-A9000 Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; SM-C5000 Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; SM-C7000 Build/MMB29M")
            .add("Linux; Android 6.0.1; SM-C7000 Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; SM-C9000 Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; SM-G9250 Build/MMB29K; wv")
            .add("Linux; Android 6.0.1; SM-G9280 Build/MMB29K; wv")
            .add("Linux; Android 6.0.1; SM-G9300 Build/MMB29M")
            .add("Linux; Android 6.0.1; SM-G9350 Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; SM-N9200 Build/MMB29K; wv")
            .add("Linux; Android 6.0.1; vivo X9 Build/MMB29M")
            .add("Linux; Android 6.0.1; vivo X9 Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; vivo X9Plus Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; vivo X9Plus L Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; vivo Y66 Build/MMB29M; wv")
            .add("Linux; Android 6.0.1; vivo Y66L Build/MMB29M; wv")
            .add("Linux; Android 6.0; ALE-TL00 Build/HuaweiALE-TL00; wv")
            .add("Linux; Android 6.0; EDI-AL10 Build/HUAWEIEDISON-AL10; wv")
            .add("Linux; Android 6.0; FRD-AL00 Build/HUAWEIFRD-AL00; wv")
            .add("Linux; Android 6.0; FRD-AL10 Build/HUAWEIFRD-AL10")
            .add("Linux; Android 6.0; HUAWEI MLA-AL10 Build/HUAWEIMLA-AL10; wv")
            .add("Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv")
            .add("Linux; Android 6.0; MI 5 Build/MRA58K; wv")
            .add("Linux; Android 6.0; MX6 Build/MRA58K")
            .add("Linux; Android 6.0; MX6 Build/MRA58K; wv")
            .add("Linux; Android 6.0; NEM-AL10 Build/HONORNEM-AL10; wv")
            .add("Linux; Android 6.0; NEM-TL00H Build/HONORNEM-TL00H; wv")
            .add("Linux; Android 6.0; PLK-AL10 Build/HONORPLK-AL10; wv")
            .add("Linux; Android 6.0; PLK-UL00 Build/HONORPLK-UL00; wv")
            .add("Linux; Android 6.0; PRO 6 Build/MRA58K; wv")
            .add("Linux; Android 6.0; Redmi Note 4 Build/MRA58K; wv")
            .add("Linux; Android 6.0; vivo Y67 Build/MRA58K; wv")
            .add("Linux; Android 6.0; vivo Y67L Build/MRA58K")
            .add("Linux; Android 7.0; BLN-AL10 Build/HONORBLN-AL10; wv")
            .add("Linux; Android 7.0; BLN-TL10 Build/HONORBLN-TL10; wv")
            .add("Linux; Android 7.0; DUK-AL20 Build/HUAWEIDUK-AL20; wv")
            .add("Linux; Android 7.0; EVA-AL00 Build/HUAWEIEVA-AL00; wv")
            .add("Linux; Android 7.0; EVA-AL10 Build/HUAWEIEVA-AL10; wv")
            .add("Linux; Android 7.0; EVA-DL00 Build/HUAWEIEVA-DL00; wv")
            .add("Linux; Android 7.0; FRD-AL00 Build/HUAWEIFRD-AL00; wv")
            .add("Linux; Android 7.0; FRD-AL10 Build/HUAWEIFRD-AL10; wv")
            .add("Linux; Android 7.0; HUAWEI MLA-AL10 Build/HUAWEIMLA-AL10; wv")
            .add("Linux; Android 7.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv")
            .add("Linux; Android 7.0; HUAWEI NXT-DL00 Build/HUAWEINXT-DL00; wv")
            .add("Linux; Android 7.0; HUAWEI NXT-TL00 Build/HUAWEINXT-TL00; wv")
            .add("Linux; Android 7.0; KNT-AL20 Build/HUAWEIKNT-AL20; wv")
            .add("Linux; Android 7.0; KNT-UL10 Build/HUAWEIKNT-UL10; wv")
            .add("Linux; Android 7.0; MHA-AL00 Build/HUAWEIMHA-AL00")
            .add("Linux; Android 7.0; MHA-AL00 Build/HUAWEIMHA-AL00; wv")
            .add("Linux; Android 7.0; MI 4S Build/NRD90M; wv")
            .add("Linux; Android 7.0; MI 5 Build/NRD90M; wv")
            .add("Linux; Android 7.0; MI MAX Build/NRD90M; wv")
            .add("Linux; Android 7.0; PRA-AL00 Build/HONORPRA-AL00")
            .add("Linux; Android 7.0; PRA-AL00 Build/HONORPRA-AL00; wv")
            .add("Linux; Android 7.0; SM-G9308 Build/NRD90M; wv")
            .add("Linux; Android 7.0; SM-G9350 Build/NRD90M")
            .add("Linux; Android 7.0; VTR-TL00 Build/HUAWEIVTR-TL00; wv")
            .add("Linux; Android 7.1.1; OPPO R11t Build/NMF26X; wv")
            .add("Linux; U; Android 4.4.2; zh-CN; H60-L01 Build/HDH60-L01")
            .add("Linux; U; Android 4.4.2; zh-CN; HUAWEI MT7-TL00 Build/HuaweiMT7-TL00")
            .add("Linux; U; Android 4.4.2; zh-CN; SM-N9008S Build/KOT49H")
            .add("Linux; U; Android 4.4.2; zh-cn; 2014501 Build/KOT49H")
            .add("Linux; U; Android 4.4.2; zh-cn; MX4 Build/KOT49H")
            .add("Linux; U; Android 4.4.2; zh-cn; SCH-I959 Build/KOT49H")
            .add("Linux; U; Android 4.4.2; zh-cn; SM-N9006 Build/KOT49H")
            .add("Linux; U; Android 4.4.2; zh-cn; SM-N9008V Build/KOT49H")
            .add("Linux; U; Android 4.4.2; zh-cn; SM701 Build/SANFRANCISCO")
            .add("Linux; U; Android 4.4.4; zh-cn; HM 2A Build/KTU84Q")
            .add("Linux; U; Android 4.4.4; zh-cn; HM NOTE 1LTE Build/KTU84P")
            .add("Linux; U; Android 4.4.4; zh-cn; HM NOTE 1S Build/KTU84P")
            .add("Linux; U; Android 4.4.4; zh-cn; MI 4W Build/KTU84P")
            .add("Linux; U; Android 4.4.4; zh-cn; MI NOTE LTE Build/KTU84P")
            .add("Linux; U; Android 4.4.4; zh-cn; OPPO R7 Build/KTU84P")
            .add("Linux; U; Android 4.4.4; zh-cn; SM-A5000 Build/KTU84P")
            .add("Linux; U; Android 4.4.4; zh-cn; SM-E7000 Build/KTU84P")
            .add("Linux; U; Android 4.4.4; zh-cn; X9007 Build/KTU84P")
            .add("Linux; U; Android 5.0.1; zh-CN; MX5 Build/LRX22C")
            .add("Linux; U; Android 5.0.1; zh-cn; MX5 Build/LRX22C")
            .add("Linux; U; Android 5.0.1; zh-cn; SCH-I959 Build/LRX22C")
            .add("Linux; U; Android 5.0.2; zh-CN; Redmi Note 2 Build/LRX22G")
            .add("Linux; U; Android 5.0.2; zh-CN; Redmi Note 3 Build/LRX22G")
            .add("Linux; U; Android 5.0.2; zh-cn; MI 2S Build/LRX22G")
            .add("Linux; U; Android 5.0.2; zh-cn; MI NOTE Pro Build/LRX22G")
            .add("Linux; U; Android 5.0.2; zh-cn; Redmi Note 2 Build/LRX22G")
            .add("Linux; U; Android 5.0.2; zh-cn; Redmi Note 3 Build/LRX22G")
            .add("Linux; U; Android 5.0; zh-cn; SM-G9009D Build/LRX21T")
            .add("Linux; U; Android 5.0; zh-cn; SM-N9008S Build/LRX21V")
            .add("Linux; U; Android 5.0; zh-cn; SM-N9008V Build/LRX21V")
            .add("Linux; U; Android 5.1.1; en-us; Redmi Note 3 Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-CN; R7Plusm Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-CN; SM801 Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-CN; YQ601 Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-CN; vivo X7 Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-cn; MI 4S Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-cn; MI NOTE Pro Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-cn; MX4 Pro Build/LMY48W")
            .add("Linux; U; Android 5.1.1; zh-cn; OPPO R7sm Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-cn; OPPO R9 Plusm A Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-cn; OPPO R9 Plustm A Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-cn; Redmi 3 Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-cn; Redmi Note 3 Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-cn; SM-A8000 Build/LMY47X")
            .add("Linux; U; Android 5.1.1; zh-cn; SM801 Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-cn; YQ601 Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-cn; vivo X7 Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-cn; vivo X7Plus Build/LMY47V")
            .add("Linux; U; Android 5.1.1; zh-cn; vivo Xplay5A Build/LMY47V")
            .add("Linux; U; Android 5.1; zh-CN; MX4 Build/LMY47I")
            .add("Linux; U; Android 5.1; zh-CN; MX5 Build/LMY47I")
            .add("Linux; U; Android 5.1; zh-CN; PRO 5 Build/LMY47D")
            .add("Linux; U; Android 5.1; zh-CN; m1 metal Build/LMY47I")
            .add("Linux; U; Android 5.1; zh-CN; m2 note Build/LMY47D")
            .add("Linux; U; Android 5.1; zh-cn; MX4 Build/LMY47I")
            .add("Linux; U; Android 5.1; zh-cn; MX5 Build/LMY47I")
            .add("Linux; U; Android 5.1; zh-cn; OPPO A59s Build/LMY47I")
            .add("Linux; U; Android 5.1; zh-cn; OPPO R9m Build/LMY47I")
            .add("Linux; U; Android 5.1; zh-cn; OPPO R9tm Build/LMY47I")
            .add("Linux; U; Android 5.1; zh-cn; PRO 5 Build/LMY47D")
            .add("Linux; U; Android 5.1; zh-cn; m1 metal Build/LMY47I")
            .add("Linux; U; Android 5.1; zh-cn; m2 note Build/LMY47D")
            .add("Linux; U; Android 5.1; zh-hk; MX4 Build/LMY47I")
            .add("Linux; U; Android 6.0.1; zh-CN; MI 4LTE Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; MI 5 Build/MXB48T")
            .add("Linux; U; Android 6.0.1; zh-CN; MI 5s Plus Build/MXB48T")
            .add("Linux; U; Android 6.0.1; zh-CN; MI NOTE LTE Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; MIX Build/MXB48T")
            .add("Linux; U; Android 6.0.1; zh-CN; OPPO R9s Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; Redmi 3S Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; Redmi 4 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; Redmi 4X Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; Redmi Note 3 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; Redmi Note 4X Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; SM-A8000 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; SM-A9000 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; SM-A9100 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; SM-C5000 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; SM-C7000 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; SM-C9000 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; SM-G9009W Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; SM-G9250 Build/MMB29K")
            .add("Linux; U; Android 6.0.1; zh-CN; SM-G9280 Build/MMB29K")
            .add("Linux; U; Android 6.0.1; zh-CN; SM-G9350 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-CN; vivo X9 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-TW; Redmi 3S Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; HUAWEI RIO-AL00 Build/HuaweiRIO-AL00")
            .add("Linux; U; Android 6.0.1; zh-cn; MI 3W Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; MI 4LTE Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; MI 4W Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; MI 5 Build/MXB48T")
            .add("Linux; U; Android 6.0.1; zh-cn; MI 5s Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; MI 5s Build/MXB48T")
            .add("Linux; U; Android 6.0.1; zh-cn; MI 5s Plus Build/MXB48T")
            .add("Linux; U; Android 6.0.1; zh-cn; MI MAX Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; MI NOTE LTE Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; OPPO A57 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; OPPO R9s Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; OPPO R9s Plus Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; OPPO R9sk Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; OPPO R9st Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; Redmi 3S Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; Redmi 3X Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; Redmi 4 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; Redmi 4A Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; Redmi 4X Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; Redmi Note 3 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; Redmi Note 4X Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; SM-A8000 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; SM-A9000 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; SM-A9100 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; SM-C5000 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; SM-C7000 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; SM-C9000 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; SM-G9250 Build/MMB29K")
            .add("Linux; U; Android 6.0.1; zh-cn; SM-G9280 Build/MMB29K")
            .add("Linux; U; Android 6.0.1; zh-cn; SM-G9308 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; SM-G9350 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; SM-N9200 Build/MMB29K")
            .add("Linux; U; Android 6.0.1; zh-cn; SM919 Build/MXB48T")
            .add("Linux; U; Android 6.0.1; zh-cn; vivo X9 Build/MMB29M")
            .add("Linux; U; Android 6.0.1; zh-cn; vivo Xplay6 Build/MXB48T")
            .add("Linux; U; Android 6.0.1; zh-tw; SM-G9250 Build/MMB29K")
            .add("Linux; U; Android 6.0; zh-CN; CHM-TL00H Build/HonorCHM-TL00H")
            .add("Linux; U; Android 6.0; zh-CN; H60-L01 Build/HDH60-L01")
            .add("Linux; U; Android 6.0; zh-CN; HUAWEI CRR-UL00 Build/HUAWEICRR-UL00")
            .add("Linux; U; Android 6.0; zh-CN; HUAWEI MT7-CL00 Build/HuaweiMT7-CL00")
            .add("Linux; U; Android 6.0; zh-CN; MX6 Build/MRA58K")
            .add("Linux; U; Android 6.0; zh-CN; NEM-AL10 Build/HONORNEM-AL10")
            .add("Linux; U; Android 6.0; zh-CN; PLK-TL01H Build/HONORPLK-TL01H")
            .add("Linux; U; Android 6.0; zh-CN; PLK-UL00 Build/HONORPLK-UL00")
            .add("Linux; U; Android 6.0; zh-TW; HUAWEI MT7-TL10 Build/HuaweiMT7-TL10")
            .add("Linux; U; Android 6.0; zh-cn; CAM-AL00 Build/HONORCAM-AL00")
            .add("Linux; U; Android 6.0; zh-cn; HUAWEI MT7-TL10 Build/HuaweiMT7-TL10")
            .add("Linux; U; Android 6.0; zh-cn; MI 5 Build/MRA58K")
            .add("Linux; U; Android 6.0; zh-cn; MX6 Build/MRA58K")
            .add("Linux; U; Android 6.0; zh-cn; PRO 6 Build/MRA58K")
            .add("Linux; U; Android 6.0; zh-cn; Redmi Note 4 Build/MRA58K")
            .add("Linux; U; Android 6.0; zh-cn; Redmi Pro Build/MRA58K")
            .add("Linux; U; Android 6.0; zh-cn; vivo Y67 Build/MRA58K")
            .add("Linux; U; Android 7.0; zh-CN; BLN-AL10 Build/HONORBLN-AL10")
            .add("Linux; U; Android 7.0; zh-CN; EVA-AL00 Build/HUAWEIEVA-AL00")
            .add("Linux; U; Android 7.0; zh-CN; EVA-AL10 Build/HUAWEIEVA-AL10")
            .add("Linux; U; Android 7.0; zh-CN; FRD-AL10 Build/HUAWEIFRD-AL10")
            .add("Linux; U; Android 7.0; zh-CN; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10")
            .add("Linux; U; Android 7.0; zh-CN; HUAWEI NXT-DL00 Build/HUAWEINXT-DL00")
            .add("Linux; U; Android 7.0; zh-CN; KNT-UL10 Build/HUAWEIKNT-UL10")
            .add("Linux; U; Android 7.0; zh-CN; MHA-AL00 Build/HUAWEIMHA-AL00")
            .add("Linux; U; Android 7.0; zh-CN; MI 5 Build/NRD90M")
            .add("Linux; U; Android 7.0; zh-CN; MI NOTE Pro Build/NRD90M")
            .add("Linux; U; Android 7.0; zh-CN; Mi-4c Build/NRD90M")
            .add("Linux; U; Android 7.0; zh-CN; SM-G9300 Build/NRD90M")
            .add("Linux; U; Android 7.0; zh-CN; SM-G9350 Build/NRD90M")
            .add("Linux; U; Android 7.0; zh-CN; VIE-AL10 Build/HUAWEIVIE-AL10")
            .add("Linux; U; Android 7.0; zh-cn; BLN-AL20 Build/HONORBLN-AL20")
            .add("Linux; U; Android 7.0; zh-cn; DUK-AL20 Build/HUAWEIDUK-AL20")
            .add("Linux; U; Android 7.0; zh-cn; EVA-AL10 Build/HUAWEIEVA-AL10")
            .add("Linux; U; Android 7.0; zh-cn; FRD-AL00 Build/HUAWEIFRD-AL00")
            .add("Linux; U; Android 7.0; zh-cn; HUAWEI NXT-DL00 Build/HUAWEINXT-DL00")
            .add("Linux; U; Android 7.0; zh-cn; LON-AL00 Build/HUAWEILON-AL00")
            .add("Linux; U; Android 7.0; zh-cn; MHA-AL00 Build/HUAWEIMHA-AL00")
            .add("Linux; U; Android 7.0; zh-cn; MI 5 Build/NRD90M")
            .add("Linux; U; Android 7.0; zh-cn; MI 5s Build/NRD90M")
            .add("Linux; U; Android 7.0; zh-cn; MI MAX Build/NRD90M")
            .add("Linux; U; Android 7.0; zh-cn; Mi-4c Build/NRD90M")
            .add("Linux; U; Android 7.0; zh-cn; VKY-AL00 Build/HUAWEIVKY-AL00")
            .build();

    ImmutableList<String> chromeVersions = ImmutableList.<String>builder()
            .add("55.0.2883.95")
            .add("52.0.2743.116")
            .add("52.0.2743.116")
            .add("52.0.2743.82")
            .add("52.0.2743.82")
            .add("46.0.2490.86")
            .add("46.0.2490.86")
            .add("45.0.2454.85")
            .add("45.0.2454.85")
            .add("39.0.2171.71")
            .add("39.0.2171.65")
            .add("38.0.2125.122")
            .add("36.0.1985.125")
            .add("35.0.1916.114")
            .add("34.0.1847.116")
            .add("33.0.1750.117")
            .add("32.0.1700.76")
            .add("31.0.1650.63")
            .add("31.0.1650.57")
            .add("31.0.1650.48")
            .add("30.0.1599.101")
            .add("30.0.1599.69")
            .add("29.0.1547.66")
            .add("29.0.1547.76")
            .add("29.0.1547.62")
            .add("29.0.1547.57")
            .add("28.0.1500.95")
            .add("28.0.1500.72")
            .add("28.0.1500.71")
            .add("27.0.1453.116")
            .add("27.0.1453.110")
            .add("27.0.1453.93")
            .add("26.0.1410.64")
            .add("19.0.1084.46")
            .add("18.0.1025.162")
            .add("18.0.1025.151")
            .add("18.0.1025.140")
            .add("17.0.963.79")
            .add("17.0.963.65")
            .add("17.0.963.46")
            .add("35.0.1916.114")
            .add("38.0.2125.122")
            .add("39.0.2171.65")
            .add("33.0.1750.154")
            .build();

    ImmutableList<String> firefoxVersions = ImmutableList.<String>builder()
            .add("20.0")
            .add("20.0b1")
            .add("20.0b2")
            .add("20.0b3")
            .add("20.0b4-funnelcake19")
            .add("20.0b4-funnelcake20")
            .add("20.0b4")
            .add("23.0")
            .add("23.0b1")
            .add("23.0b10")
            .add("24.0b6")
            .add("24.0b7")
            .add("24.0b8")
            .add("24.0b9")
            .add("24.0esr")
            .add("24.1.0esr")
            .add("24.1.1esr")
            .add("24.2.0esr")
            .add("24.3.0esr")
            .add("24.4.0esr")
            .add("24.5.0esr")
            .add("24.6.0esr")
            .add("24.7.0esr")
            .add("24.8.0esr")
            .add("24.8.1esr")
            .add("25.0.1")
            .add("25.0")
            .add("25.0b1")
            .add("25.0b10")
            .add("25.0b11")
            .add("25.0b12")
            .add("25.0b2")
            .add("25.0b3")
            .add("25.0b4")
            .add("25.0b6")
            .add("27.0b2")
            .add("27.0b4")
            .add("27.0b5")
            .add("27.0b6")
            .add("27.0b7")
            .add("27.0b8")
            .add("27.0b9")
            .add("28.0")
            .add("28.0b1")
            .add("28.0b2")
            .add("28.0b3")
            .add("3.6b5")
            .add("3.6rc1")
            .add("3.6rc2")
            .add("30.0")
            .add("30.0b1")
            .add("30.0b2")
            .add("30.0b3")
            .add("30.0b4")
            .add("30.0b5")
            .add("30.0b6")
            .add("30.0b7")
            .add("30.0b8")
            .add("30.0b9")
            .add("31.0")
            .add("31.0b1")
            .add("31.0b2")
            .add("32.0b6")
            .add("32.0b7")
            .add("32.0b8")
            .add("32.0b9")
            .add("33.0.1")
            .add("33.0.2")
            .add("33.0.3")
            .add("33.0")
            .add("33.0b1")
            .add("35.0b3")
            .add("35.0b4")
            .add("35.0b5")
            .add("35.0b6")
            .add("35.0b8")
            .add("36.0.1")
            .add("36.0.3")
            .add("36.0.4")
            .add("36.0")
            .add("43.0b4")
            .add("43.0b5")
            .add("43.0b6")
            .add("43.0b7")
            .add("43.0b8")
            .add("43.0b9")
            .add("44.0.1")
            .add("44.0.2")
            .add("44.0")
            .add("44.0b1")
            .add("44.0b2")
            .add("44.0b4")
            .add("44.0b6")
            .add("44.0b7")
            .add("44.0b8")
            .add("44.0b9")
            .add("45.0.1")
            .build();
}
